service: RobertoMadinyaLetsGoServerless
provider:
  name: aws
  region: us-east-1
  role: arn:aws:iam::859647202319:role/LetsGoServerlessLambdaExecution
  runtime: python3.8
  timeout: 360
functions:
  RobertoMadinyaSuma:
    name: RobertoMadinyaSuma
    handler: lambda_handler.suma
    environment:
      PASSWORD: contrasena-de-algo
      BACKEND: http://www.google.com
    maximumRetryAttempts: 0
    description: Funcion que toma dos operandos y devuelve la suma
  RobertoMadinyaResta:
    name: RobertoMadinyaResta
    handler: lambda_handler.resta
    environment:
      PASSWORD: contrasena-de-algo
      BACKEND: http://www.google.com
    maximumRetryAttempts: 0
    description: Funcion que toma dos operandos y devuelve la resta
package:
  patterns:
    - "!node_modules/**"
    - "!venv/**"
